### ISSUE TITLE
Container crash

### ISSUE THREAD

**Issue by arthurio** [pavanputhra/logspout-signoz#10]
On one of the instance I try to run the container I get the following error (the container crashes and exits):

```bash
logspout-1  | panic: interface conversion: interface {} is float64, not string
logspout-1  |
logspout-1  | goroutine 23 [running]:
logspout-1  | github.com/pavanputhra/logspout-signoz/signoz.(*Adapter).Stream(0xc0000b2760, 0xc000094300)
logspout-1  | 	/root/go/pkg/mod/github.com/pavanputhra/logspout-signoz@v0.0.0-20250201135552-f76f00fce88f/signoz/signoz.go:173 +0x11f0
logspout-1  | github.com/gliderlabs/logspout/router.(*RouteManager).route(0xc0000a7830, 0xc0000d8370)
logspout-1  | 	/src/router/routes.go:164 +0xbd
logspout-1  | github.com/gliderlabs/logspout/router.(*RouteManager).Run.func1(0xc0000a7830, 0xc0000d8370)
logspout-1  | 	/src/router/routes.go:190 +0x35
logspout-1  | created by github.com/gliderlabs/logspout/router.(*RouteManager).Run
logspout-1  | 	/src/router/routes.go:189 +0xeb
logspout-1 exited with code 2
```

**Comment by pavanputhra** [comment]
@arthurio Could you please send the logs which your container produce. So that I can test against it?

**Comment by arthurio** [comment]
@pavanputhra I'll try to isolate which of the containers is triggering the issue first and keep you posted.

**Comment by arthurio** [comment]
I'm still trying to identify which container is causing the issue. I have updated the image to `2025.06.24-b67c6a8` and I now get:

```bash
logspout-1  | goroutine 10 [running]:
logspout-1  | github.com/pavanputhra/logspout-signoz/signoz.(*Adapter).Stream(0xc0000207e0, 0xc00009a300)
logspout-1  | 	/root/go/pkg/mod/github.com/pavanputhra/logspout-signoz@v0.0.0-20250613211211-160a9c14d250/signoz/signoz.go:201 +0x1220
logspout-1  | github.com/gliderlabs/logspout/router.(*RouteManager).route(0xc0000a5830, 0xc0000ca370)
logspout-1  | 	/src/router/routes.go:164 +0xbd
logspout-1  | github.com/gliderlabs/logspout/router.(*RouteManager).Run.func1(0xc0000a5830, 0xc0000ca370)
logspout-1  | 	/src/router/routes.go:190 +0x35
logspout-1  | created by github.com/gliderlabs/logspout/router.(*RouteManager).Run
logspout-1  | 	/src/router/routes.go:189 +0xeb
logspout-1 exited with code 2
```

So it would mean that [`level = jsonMap["level"].(string)`](https://github.com/pavanputhra/logspout-signoz/blob/main/signoz/signoz.go#L201) is somehow a float.

**Comment by arthurio** [comment]
Yeah I found the culprit, it's [supabase](https://github.com/supabase/supabase), here is a redacted log:

```bash
{
  "log":{
    "level":40,
    "time":"2025-04-20T20:40:16.188Z",
    "pid":1,
    "hostname":"xxxxxx",
    "region":"stub",
    "tenantId":"stub",
    "project":"stub",
    "type":"request",
    "req": {
      "region":"stub",
      "method":"POST",
      "url":"/bucket",
      "headers": {
        "host":"[REDACTED]",
        "x_forwarded_proto":"http",
        "x_forwarded_prefix":"/storage/v1/",
        "content_length":"59",
        "accept":"*/*",
        "user_agent":"supabase-py/storage3 v0.11.3",
        "x_client_info":"supabase-py/2.13.0",
        "content_type":"application/json"
      },
      "hostname": "[REDACTED]",
    },
    "res":{
      "statusCode":400,
      "headers":{
        "content_type":"application/json; charset=utf-8",
        "content_length":"80"
      }
    },
    "responseTime":3.7509701251983643,
  },
  "stream":"stdout",
  "time":"2025-04-20T20:40:16.188318015Z"
}
```

**Comment by arthurio** [comment]
FYI, I have tried to add the following to the container with the offending logs but it still breaks logspout:

```yaml
    labels:
      logspout.exclude: "true"
```

**Comment by pavanputhra** [comment]
@arthurio

Fixed in `pavanputhra/logspout-signoz:2025.07.12-887dfeb`.

Details: Previously, if the JSON log contained an unexpected type—for example, `"level": 40` (integer) instead of a string like `"level": "info"`—the code would crash. This has now been fixed by adding proper type checking.

**Comment by arthurio** [comment]
@pavanputhra Thank you so much for the quick fix 🙏🏻

**Comment by arthurio** [comment]
@pavanputhra I just tested, and I seem to still get the error:

```bash
logspout-1  | panic: interface conversion: interface {} is float64, not string
logspout-1  |
logspout-1  | goroutine 10 [running]:
logspout-1  | github.com/pavanputhra/logspout-signoz/signoz.(*Adapter).Stream(0xc000020660, 0xc00009a300)
logspout-1  | 	/root/go/pkg/mod/github.com/pavanputhra/logspout-signoz@v0.0.0-20250624125509-b67c6a859fdc/signoz/signoz.go:201 +0x1220
logspout-1  | github.com/gliderlabs/logspout/router.(*RouteManager).route(0xc0000a5830, 0xc0000ca370)
logspout-1  | 	/src/router/routes.go:164 +0xbd
logspout-1  | github.com/gliderlabs/logspout/router.(*RouteManager).Run.func1(0xc0000a5830, 0xc0000ca370)
logspout-1  | 	/src/router/routes.go:190 +0x35
logspout-1  | created by github.com/gliderlabs/logspout/router.(*RouteManager).Run
logspout-1  | 	/src/router/routes.go:189 +0xeb
```

**Comment by pavanputhra** [comment]
Hey @arthurio , try the docker image tag `2025.07.19-887dfeb`. It should fix the issue.

> Note: Looks like there is some bug in my GitHub Action code, which takes previous commit instead of current commit code to build image. Need to figure it out.

**Comment by arthurio** [comment]
I confirm that `2025.07.19-887dfeb` is working as expected 👍🏻 Good luck fixing your Github Action 😄

**Comment by pavanputhra** [comment]
The crash fix shipped in v1; [v2.0.0](https://github.com/pavanputhra/logspout-signoz/releases/tag/v2.0.0) now handles that log line properly rather than just surviving it.

`{"level":40,...}` is pino, which uses numeric levels. v1 ignored the number and left the record at `info`, with `40` pushed into attributes. v2 maps the pino/bunyan scale (10 trace through 60 fatal), so that line arrives as `warn`.

v2 also recognises `msg`, `time` and `ts`, so pino, bunyan, zap and logrus logs get a real body and timestamp instead of the whole JSON blob as the message.
